[package]
name = "of-many-things"
version = "0.1.0"
authors = ["RomanAkberov <r.k.akberov@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.17"
rand = { version = "0.7", features = ["wasm-bindgen"] }
regex = "1"