use crate::grammar::{Adjective, Animacy, Gender, Noun, NounDeclension, NounDeclensionException};
use Animacy::*;
use Gender::*;
use NounDeclension::*;
use NounDeclensionException::*;

pub const WEIRD: &[Adjective] = &[
    Adjective("непонятный"),
    Adjective("странный"),
    Adjective("загадочный"),
    Adjective("необычный"),
    Adjective("непривычный"),
    Adjective("удивительный"),
    Adjective("подозрительный"),
    Adjective("неестественный"),
    Adjective("таинственный"),
    Adjective("непостижимый"),
    Adjective("любопытный"),
];

pub const SIZE: &[Adjective] = &[
    Adjective("крохотный"),
    Adjective("миниатюрный"),
    Adjective("маленький"),
    Adjective("небольшой"),
    Adjective("тонкий"),
    Adjective("длинный"),
    Adjective("большой"),
    Adjective("толстый"),
];

pub const SHAPE: &[Adjective] = &[
    Adjective("круглый"),
    Adjective("овальный"),
    Adjective("полукруглый"),
    Adjective("треугольный"),
    Adjective("квадратный"),
    Adjective("прямоугольный"),
    Adjective("пятиугольный"),
    Adjective("шестиугольный"),
    Adjective("семиугольный"),
    Adjective("восьмиугольный"),
    Adjective("цилиндрический"),
    Adjective("несимметричный"),
    Adjective("деформированный"),
    Adjective("бесформенный"),
];

pub const FEEL: &[Adjective] = &[
    Adjective("теплый"),
    Adjective("холодный"),
    Adjective("мягкий"),
    Adjective("твердый"),
    Adjective("пористый"),
    Adjective("шершавый"),
    Adjective("гладкий"),
];

pub const COLOR: &[Adjective] = &[
    Adjective("светлый"),
    Adjective("темный"),
    Adjective("красный"),
    Adjective("зелёный"),
    Adjective("синий"),
    Adjective("белый"),
    Adjective("серый"),
    Adjective("черный"),
    Adjective("розовый"),
    Adjective("фиолетовый"),
    Adjective("оранжевый"),
    Adjective("желтый"),
    Adjective("голубой"),
    Adjective("алый"),
    Adjective("тёмно-красный"),
    Adjective("ярко-красный"),
    Adjective("кроваво-красный"),
    Adjective("малиновый"),
    Adjective("пурпурный"),
    Adjective("багровый"),
    Adjective("огненно-красный"),
    Adjective("бледно-розовый"),
    Adjective("карминовый"),
    Adjective("жёлто-зелёный"),
    Adjective("сине-зеленый"),
    Adjective("неяркий"),
    Adjective("матовый"),
    Adjective("бледный"),
    Adjective("яркий"),
    Adjective("тусклый"),
    Adjective("разноцветный"),
    Adjective("невидимый"),
    Adjective("прозрачный"),
    Adjective("полупрозрачный"),
    Adjective("светящийся"),
    Adjective("блестящий"),
];

pub const MATERIAL: &[Adjective] = &[
    Adjective("металлический"),
    Adjective("золотой"),
    Adjective("серебряный"),
    Adjective("бронзовый"),
    Adjective("медный"),
    Adjective("стальной"),
    Adjective("железный"),
    Adjective("платиновый"),
    Adjective("оловянный"),
    Adjective("латунный"),
    Adjective("каменный"),
    Adjective("мраморный"),
    Adjective("гранитный"),
    Adjective("нефритовый"),
    Adjective("стеклянный"),
    Adjective("хрустальный"),
    Adjective("янтарный"),
    Adjective("зеркальный"),
    Adjective("синтовый"),
    Adjective("резиновый"),
    Adjective("тканевый"),
    Adjective("льняной"),
    Adjective("шелковый"),
    Adjective("вязаный"),
    Adjective("кожаный"),
    Adjective("деревянный"),
    Adjective("соломенный"),
    Adjective("органический"),
    Adjective("керамический"),
    Adjective("глиняный"),
    Adjective("бумажный"),
    Adjective("картонный"),
];

pub const OBJECTS: &[Noun] = &[
    // Noun::new("птиц", Feminine, Animate, T5, Regular),
    Noun::new("лягушка", Feminine, Animate, T3, FluentVowel('е')),
    Noun::new("осьминог", Masculine, Animate, T3, Regular),
    Noun::new("череп", Masculine, Inanimate, T1, Plural("а")),
    Noun::new("рог", Masculine, Inanimate, T3, Plural("а")),
    Noun::new("игрушка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("орнитоптер", Masculine, Inanimate, T1, Regular),
    Noun::new("карточка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("подушка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("одеяло", Neuter, Inanimate, T1, Regular),
    Noun::new("седло", Neuter, Inanimate, T1, FluentVowel('е')),
    // Noun::new("стул", Masculine, Inanimate, T1, Regular), // not regular
    // Noun::new("прут", Masculine, Inanimate, T1, Regular), // not regular
    Noun::new("шнур", Masculine, Inanimate, T1, Regular),
    Noun::new("цветок", Masculine, Inanimate, T3, FluentVowel('о')),
    Noun::new("роза", Feminine, Inanimate, T1, Regular),
    Noun::new("палочка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("стержень", Masculine, Inanimate, T2, FluentVowel('е')),
    Noun::new("кабель", Masculine, Inanimate, T2, Regular),
    Noun::new("лист", Masculine, Inanimate, T1, Regular),
    Noun::new("шланг", Masculine, Inanimate, T3, Regular),
    Noun::new("сота", Feminine, Inanimate, T1, Regular),
    Noun::new("линза", Feminine, Inanimate, T1, Regular),
    Noun::new("торнадо", Neuter, Inanimate, T0, Regular),
    // Noun::new("пуговица", "f"),
    // Noun::new("растение", "n"),
    Noun::new("башенка", Feminine, Inanimate, T3, FluentVowel('о')),
    // Noun::new("лезвие", "n"]
    Noun::new("шляпа", Feminine, Inanimate, T1, Regular),
    Noun::new("маска", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("корона", Feminine, Inanimate, T1, Regular),
    Noun::new("парик", Masculine, Inanimate, T3, Regular),
    //Noun::new("венец", "m"),
    Noun::new("шлем", Masculine, Inanimate, T1, Regular),
    Noun::new("рубашка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("пояс", Masculine, Inanimate, T1, Plural("а")),
    Noun::new("шарф", Masculine, Inanimate, T1, Regular),
    Noun::new("перчатка", Feminine, Inanimate, T3, FluentVowel('о')),
    //Noun::new("плащ", "m"),
    //Noun::new("кольцо", "n"),
    Noun::new("браслет", Masculine, Inanimate, T1, Regular),
    Noun::new("перстень", Masculine, Inanimate, T2, FluentVowel('е')),
    Noun::new("амулет", Masculine, Inanimate, T1, Regular),
    Noun::new("кулон", Masculine, Inanimate, T1, Regular),
    Noun::new("подвеска", Feminine, Inanimate, T3, FluentVowel('о')),
    //Noun::new("ожерелье", Neuter, Inanimate, T2, Regular),
    //Noun::new("колье", "n"),
    //Noun::new("ножной браслет", "m"),
    Noun::new("тиара", Feminine, Inanimate, T1, Regular),
    Noun::new("серьга", Feminine, Inanimate, T3, Regular),
    //Noun::new("брошь", "f"),
    Noun::new("помандер", Masculine, Inanimate, T1, Regular),
    Noun::new("куб", Masculine, Inanimate, T1, Regular),
    Noun::new("пирамидка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("семигранник", Masculine, Inanimate, T3, Regular),
    Noun::new("двенадцатигранник", Masculine, Inanimate, T3, Regular),
    Noun::new("ромбоид", Masculine, Inanimate, T1, Regular),
    Noun::new("антипризма", Feminine, Inanimate, T1, Regular),
    Noun::new("призма", Feminine, Inanimate, T1, Regular),
    Noun::new("шар", Masculine, Inanimate, T1, Regular),
    Noun::new("сфера", Feminine, Inanimate, T1, Regular),
    //Noun::new("полушарие", "n"),
    Noun::new("пластинка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("плитка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("диск", Masculine, Inanimate, T3, Regular),
    Noun::new("квадрат", Masculine, Inanimate, T1, Regular),
    Noun::new("звезда", Feminine, Inanimate, T1, Regular),
    Noun::new("многоугольник", Masculine, Inanimate, T3, Regular),
    Noun::new("ромб", Masculine, Inanimate, T1, Regular),
    Noun::new("алмаз", Masculine, Inanimate, T1, Regular),
    Noun::new("камень", Masculine, Inanimate, T2, FluentVowel('е')),
    Noun::new("кристалл", Masculine, Inanimate, T1, Regular),
    Noun::new("глина", Feminine, Inanimate, T1, Regular),
    //Noun::new("волос", ),
    //Noun::new("шерсть", "m"),
    //        Noun::new("слизь", "f"),
    //        Noun::new("кусок фетра", "m"),
    Noun::new("желе", Neuter, Inanimate, T0, Regular),
    Noun::new("шило", Neuter, Inanimate, T1, Regular),
    Noun::new("долото", Neuter, Inanimate, T1, Regular),
    //Noun::new("иголка с ниткой", "f"),
    Noun::new("щетка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("кисточка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("расческа", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("устройство", Neuter, Inanimate, T1, Regular),
    Noun::new("прибор", Masculine, Inanimate, T1, Regular),
    //Noun::new("музыкальный инструмент", "m"),
    Noun::new("флейта", Feminine, Inanimate, T1, Regular),
    Noun::new("арфа", Feminine, Inanimate, T1, Regular),
    Noun::new("колокольчик", Masculine, Inanimate, T3, Regular),
    Noun::new("магнит", Masculine, Inanimate, T1, Regular),
    //Noun::new("клин", "m"),
    Noun::new("дырокол", Masculine, Inanimate, T1, Regular),
    Noun::new("зеркало", Neuter, Inanimate, T1, Regular),
    Noun::new("ложка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("вилка", Feminine, Inanimate, T3, FluentVowel('о')),
    //Noun::new("рукоять", "f"),
    Noun::new("стилус", Masculine, Inanimate, T1, Regular),            
    Noun::new("контейнер", Masculine, Inanimate, T1, Regular), 
    Noun::new("клетка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("горшок", Masculine, Inanimate, T3, FluentVowel('о')),
    Noun::new("бокал", Masculine, Inanimate, T1, Regular), 
    Noun::new("сосуд", Masculine, Inanimate, T1, Regular), 
    Noun::new("коробок", Masculine, Inanimate, T3, FluentVowel('о')),
    Noun::new("тюбик", Masculine, Inanimate, T3, Regular), 
    Noun::new("коробочка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("банка", Feminine, Inanimate, T3, FluentVowel('о')),
    //Noun::new("чаша", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("чашка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("кружка", Feminine, Inanimate, T3, FluentVowel('е')),
    Noun::new("тарелка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("бутылка", Feminine, Inanimate, T3, FluentVowel('о')),
    Noun::new("ракушка", Feminine, Inanimate, T3, FluentVowel('е')),
];
