use crate::grammar::{Adjective, Animacy, Gender, Noun};
use Animacy::*;
use Gender::*;

pub const WEIRD: &[Adjective] = &[
    Adjective("непонятный"),
    Adjective("странный"),
    Adjective("загадочный"),
    Adjective("необычный"),
    Adjective("непривычный"),
    Adjective("удивительный"),
    Adjective("подозрительный"),
    Adjective("неестественный"),
    Adjective("таинственный"),
    Adjective("непостижимый"),
    Adjective("любопытный"),
];

pub const SIZE: &[Adjective] = &[
    Adjective("крохотный"),
    Adjective("миниатюрный"),
    Adjective("маленький"),
    Adjective("небольшой"),
    Adjective("тонкий"),
    Adjective("длинный"),
    Adjective("большой"),
    Adjective("толстый"),
];

pub const SHAPE: &[Adjective] = &[
    Adjective("круглый"),
    Adjective("овальный"),
    Adjective("полукруглый"),
    Adjective("треугольный"),
    Adjective("квадратный"),
    Adjective("прямоугольный"),
    Adjective("пятиугольный"),
    Adjective("шестиугольный"),
    Adjective("семиугольный"),
    Adjective("восьмиугольный"),
    Adjective("цилиндрический"),
    Adjective("несимметричный"),
    Adjective("деформированный"),
    Adjective("бесформенный"),
];

pub const FEEL: &[Adjective] = &[
    Adjective("теплый"),
    Adjective("холодный"),
    Adjective("мягкий"),
    Adjective("твердый"),
    Adjective("пористый"),
    Adjective("шершавый"),
    Adjective("гладкий"),
];

pub const COLOR: &[Adjective] = &[
    Adjective("светлый"),
    Adjective("темный"),
    Adjective("красный"),
    Adjective("зелёный"),
    Adjective("синий"),
    Adjective("белый"),
    Adjective("серый"),
    Adjective("черный"),
    Adjective("розовый"),
    Adjective("фиолетовый"),
    Adjective("оранжевый"),
    Adjective("желтый"),
    Adjective("голубой"),
    Adjective("алый"),
    Adjective("тёмно-красный"),
    Adjective("ярко-красный"),
    Adjective("кроваво-красный"),
    Adjective("малиновый"),
    Adjective("пурпурный"),
    Adjective("багровый"),
    Adjective("огненно-красный"),
    Adjective("бледно-розовый"),
    Adjective("карминовый"),
    Adjective("жёлто-зелёный"),
    Adjective("сине-зеленый"),
    Adjective("неяркий"),
    Adjective("матовый"),
    Adjective("бледный"),
    Adjective("яркий"),
    Adjective("тусклый"),
    Adjective("разноцветный"),
    Adjective("невидимый"),
    Adjective("прозрачный"),
    Adjective("полупрозрачный"),
    Adjective("светящийся"),
    Adjective("блестящий"),
];

pub const MATERIAL: &[Adjective] = &[
    Adjective("металлический"),
    Adjective("золотой"),
    Adjective("серебряный"),
    Adjective("бронзовый"),
    Adjective("медный"),
    Adjective("стальной"),
    Adjective("железный"),
    Adjective("платиновый"),
    Adjective("оловянный"),
    Adjective("латунный"),
    Adjective("каменный"),
    Adjective("мраморный"),
    Adjective("гранитный"),
    Adjective("стеклянный"),
    Adjective("хрустальный"),
    Adjective("янтарный"),
    Adjective("зеркальный"),
    Adjective("синтовый"),
    Adjective("резиновый"),
    Adjective("тканевый"),
    Adjective("льняной"),
    Adjective("шелковый"),
    Adjective("вязаный"),
    Adjective("кожаный"),
    Adjective("деревянный"),
    Adjective("соломенный"),
    Adjective("органический"),
    Adjective("керамический"),
    Adjective("глиняный"),
    Adjective("бумажный"),
    Adjective("картонный"),
];

pub const OBJECTS: &[Noun] = &[
    Noun::new("птица", Feminine, Animate),
    Noun::new("лягушка", Feminine, Animate),
    Noun::new("осьминог", Masculine, Inanimate),
    Noun::new("череп", Masculine, Inanimate),
    Noun::new("рог", Masculine, Inanimate),
    Noun::new("игрушка", Feminine, Inanimate),
    Noun::new("орнитоптер", Masculine, Inanimate),
    Noun::new("карточка", Feminine, Inanimate),
    Noun::new("подушка", Feminine, Inanimate),
    Noun::new("одеяло", Neuter, Inanimate),
    Noun::new("седло", Neuter, Inanimate),
    Noun::new("стул", Masculine, Inanimate),
    Noun::new("прут", Masculine, Inanimate),
];
